version: '3'

services:
    laravel-vuejs:
        image: laravel-vuejs
        build:
            context: .
            dockerfile: ./docker-dev/Dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION:-8.2}
        volumes:
            - ./:/var/www/app
            - /var/www/app/vendor
        environment:
            SFTP_USERNAME: ubuntu
            SFTP_ROOT: /opt/files
            DB_CONNECTION: pgsql
            DB_HOST: 172.17.0.1
            DB_PORT: 5432
            DB_DATABASE: laravel_db
            DB_USERNAME: postgres
            DB_PASSWORD: bismillah
            QUEUE_CONNECTION: database
            SESSION_DRIVER: file
            APP_TIMEZONE: Asia/Jakarta
            APP_PLATFORM: web
        extra_hosts:
            - "internal.host:host-gateway"
        networks:
            - app-net
    nginx:
        image: nginx:alpine
        ports:
            - "${APP_PORT:-8000}:80"
        volumes:
            - ./docker-dev/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
            - ./docker-dev/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
            - ./:/var/www/app:cached
            - /var/www/app/vendor
        restart: on-failure
        depends_on:
            - laravel-vuejs
        networks:
            - app-net
    supervisor:
        image: laravel-vuejs
        environment:
            APP_URL: http://localhost

        networks:
            - app-net
        depends_on:
            - laravel-vuejs
            - nginx
        command: supervisord

networks:
    app-net:
        driver: bridge

